[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'npm install --prefix frontend',
  'npm install --prefix backend'
]

[phases.build]
cmds = [
  'npm run build'
]

[start]
cmd = 'npm start'
